#!/usr/bin/env python3
"""Collect leaf-local search-pressure labels for HalfPW search control.

This does not train or deploy anything. It samples completed DB games, probes
positions with the current Titanium binary, and writes compact JSONL rows that
can train a tiny sidecar head. Rows store move prefixes and labels only;
features are regenerated by eval-batch during training.

Interpretation: after a shallow parent search chooses to enter a child, this
label answers "how much should the engine trust the child's current eval, and
how much more budget than usual does this node deserve?"

    python training/collect_search_importance.py --limit 200 --shallow-depth 2 --deep-depth 5
"""

from __future__ import annotations

import argparse
import base64
import json
import hashlib
import math
import random
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "training"))

from datagen import DB_PATH, load_games_from_db  # noqa: E402
from engine_identity import assert_engine_ready  # noqa: E402
from move_codec import pack_moves  # noqa: E402

BIN = ROOT / "engine" / "target" / "release" / "titanium.exe"
OUT = ROOT / "training" / "data" / "search_pressure.jsonl"
INFO_RE = re.compile(r"info json (\{.*\})")
BEST_RE = re.compile(r"bestmove\s+(\S+)")
MATE = 100_000
RACE_MATE = 32_000


def score_class(score: int) -> tuple[str, int, int]:
    """Return (kind, sign, plies_or_0) for comparing engine scores sanely."""
    sign = 1 if score > 0 else -1 if score < 0 else 0
    abs_score = abs(score)
    if abs_score >= MATE - 1_000:
        return ("mate", sign, max(0, MATE - abs_score))
    if RACE_MATE - 1_000 <= abs_score <= RACE_MATE:
        return ("race", sign, max(0, RACE_MATE - abs_score))
    return ("cp", sign, 0)


def score_swing(shallow_score: int, deep_score: int) -> float:
    sk, ss, sp = score_class(shallow_score)
    dk, ds, dp = score_class(deep_score)
    if sk == dk and sk in {"mate", "race"}:
        if ss != ds:
            return 1.0
        # Same forced outcome: conversion-length disagreement is useful, but it
        # is not a centipawn eval explosion.
        return min(abs(dp - sp) / 20.0, 0.35)
    if sk != "cp" or dk != "cp":
        return 1.0
    return min(abs(deep_score - shallow_score) / 600.0, 1.0)


def probe(moves: list[str], depth: int, time_sec: float, engine: str) -> dict:
    cmd = [
        str(BIN),
        "genmove",
        "--engine",
        engine,
        "--depth",
        str(depth),
        "--time",
        str(time_sec),
        *moves,
    ]
    r = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, timeout=max(20, int(time_sec + 20)))
    if r.returncode != 0:
        raise RuntimeError((r.stderr or r.stdout).strip()[-1000:])
    info = {}
    for line in r.stderr.splitlines():
        m = INFO_RE.search(line)
        if m:
            info = json.loads(m.group(1))
    best = None
    for line in r.stdout.splitlines():
        m = BEST_RE.search(line)
        if m:
            best = m.group(1)
    return {
        "best": best,
        "score": int(info.get("rootScore", 0)),
        "score_text": str(info.get("rootScoreText", "")),
        "depth": int(info.get("searchDepth", depth)),
        "nodes": int(info.get("nodes", 0)),
        "depth_log": info.get("depthLog", []),
    }


def target_components(shallow: dict, deep: dict) -> dict:
    eval_swing = score_swing(shallow["score"], deep["score"])
    move_changed = 1.0 if shallow.get("best") != deep.get("best") else 0.0
    depth_gap = max(1, deep.get("depth", 0) - shallow.get("depth", 0))
    node_ratio = math.log1p(max(0, deep.get("nodes", 0))) / max(1.0, math.log1p(max(1, shallow.get("nodes", 1))))
    node_pressure = min(max((node_ratio - 1.0) / max(1, depth_gap), 0.0), 1.0)
    depth_log = [
        row for row in deep.get("depth_log", [])
        if int(row.get("depth", 0)) >= int(shallow.get("depth", 0))
    ]
    transitions = list(zip(depth_log, depth_log[1:]))
    iteration_flip_rate = (
        sum(str(a.get("pv", "")).split()[:1] != str(b.get("pv", "")).split()[:1] for a, b in transitions)
        / len(transitions)
        if transitions else 0.0
    )
    iteration_score_swing = (
        sum(score_swing(int(a.get("score", 0)), int(b.get("score", 0))) for a, b in transitions)
        / len(transitions)
        if transitions else 0.0
    )
    iteration_instability = 0.6 * iteration_flip_rate + 0.4 * iteration_score_swing
    instability = max(0.0, min(
        1.0,
        0.45 * eval_swing
        + 0.30 * move_changed
        + 0.15 * iteration_instability
        + 0.10 * node_pressure,
    ))
    return {
        "eval_swing": eval_swing,
        "move_changed": move_changed,
        "node_pressure": node_pressure,
        "iteration_flip_rate": iteration_flip_rate,
        "iteration_score_swing": iteration_score_swing,
        "iteration_instability": iteration_instability,
        "instability": instability,
    }


def search_pressure_target(components: dict) -> float:
    """-1 = already saturated, 0 = normal trust, +1 = this child needs extra budget."""
    return 2.0 * float(components["instability"]) - 1.0


def existing_keys(path: Path) -> set[str]:
    keys: set[str] = set()
    if not path.exists():
        return keys
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if not line.strip():
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError:
            continue
        key = row.get("moves_bin")
        if key:
            keys.add(str(key))
    return keys


def sample_prefixes(
    games,
    *,
    limit: int,
    min_ply: int,
    max_ply: int,
    seed: int,
    skip: set[str],
) -> list[tuple[list[str], int, str, str, str]]:
    rng = random.Random(seed)
    candidates = []
    for moves, outcome, src in games:
        game_key = hashlib.sha256(pack_moves(moves)).hexdigest()[:20]
        hi = min(max_ply, len(moves))
        for ply in range(min_ply, hi + 1):
            prefix = moves[:ply]
            key = base64.b64encode(pack_moves(prefix)).decode("ascii")
            if key not in skip:
                candidates.append((prefix, outcome, src, key, game_key))
    rng.shuffle(candidates)
    return candidates[:limit]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data", default=str(DB_PATH))
    ap.add_argument("--out", default=str(OUT))
    ap.add_argument("--engine", default="titanium-v15")
    ap.add_argument("--limit", type=int, default=100)
    ap.add_argument("--min-ply", type=int, default=6)
    ap.add_argument("--max-ply", type=int, default=90)
    ap.add_argument("--shallow-depth", type=int, default=2)
    ap.add_argument("--deep-depth", type=int, default=5)
    ap.add_argument("--time", type=float, default=3.0)
    ap.add_argument("--seed", type=int, default=1337)
    ap.add_argument("--no-dedupe", action="store_true", help="Allow duplicate move prefixes in output")
    args = ap.parse_args()

    assert_engine_ready(write_if_missing=True, parity=False)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    skip = set() if args.no_dedupe else existing_keys(out_path)
    games = load_games_from_db(Path(args.data))
    prefixes = sample_prefixes(
        games,
        limit=args.limit,
        min_ply=args.min_ply,
        max_ply=args.max_ply,
        seed=args.seed,
        skip=skip,
    )

    written = 0
    with out_path.open("a", encoding="utf-8") as f:
        for i, (moves, outcome, src, key, game_key) in enumerate(prefixes, 1):
            try:
                shallow = probe(moves, args.shallow_depth, args.time, args.engine)
                deep = probe(moves, args.deep_depth, args.time, args.engine)
            except Exception as e:
                print(f"skip {i}/{len(prefixes)} ply={len(moves)}: {e}", file=sys.stderr)
                continue
            if shallow.get("best") in (None, "(none)") or deep.get("best") in (None, "(none)"):
                print(f"skip {i}/{len(prefixes)} ply={len(moves)}: terminal position", file=sys.stderr)
                continue
            if score_class(shallow["score"])[0] != "cp" or score_class(deep["score"])[0] != "cp":
                print(f"skip {i}/{len(prefixes)} ply={len(moves)}: forced-result override", file=sys.stderr)
                continue
            components = target_components(shallow, deep)
            row = {
                "schema": "leaf-search-pressure-v1",
                "moves_bin": key,
                "outcome": outcome,
                "src": src,
                "source_game_key": game_key,
                "teacher": "titanium-native",
                "ply": len(moves),
                "engine": args.engine,
                "shallow": shallow,
                "deep": deep,
                "target_components": components,
                "search_pressure": search_pressure_target(components),
            }
            f.write(json.dumps(row, separators=(",", ":")) + "\n")
            f.flush()
            written += 1
            print(
                f"{written:4d} ply={len(moves):3d} pressure={row['search_pressure']:+.3f} "
                f"{shallow['best']}@d{shallow['depth']}:{shallow['score']}({shallow['score_text']}) -> "
                f"{deep['best']}@d{deep['depth']}:{deep['score']}({deep['score_text']})",
                flush=True,
            )
    print(f"wrote {written} rows -> {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
